apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.35.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # HTTP
  - containerPort: 30080
    hostPort: 80
    protocol: TCP
  # HTTPS
  - containerPort: 30443
    hostPort: 443
    protocol: TCP
  # Dapr Dashboard
  - containerPort: 30081
    hostPort: 8080
    protocol: TCP
- role: worker
  image: kindest/node:v1.35.0
- role: worker
  image: kindest/node:v1.35.0
- role: worker
  image: kindest/node:v1.35.0